### ISSUE TITLE
Add Support for multiple Base URLs

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#29]
# Feature suggestion:
Add Support for multiple Base URLs per Project. In each Action, one of the base URL should be selectable. 

# Use Case:
Imagine you want to test your Frontend and Backend, both have different URLs. You could set the Frontend URL as base URL and use absolute URL to test your Backend. You could also use absolut URLs for your Reset-API, too. 

It would be better if we could set three Base URLs in our Project and select one from a list per Action. We would be able to switch our Environments (testing, staging, production...) more easily. 
For now we have to replace the absolute URLs every time

**Comment by abainczyk** [comment]
Hi, there already is the possibility to assign multiple URLs to a project and choose, e.g. for a test execution, against which URL tests are executed. I get your point that frontend and backend may be on different servers and that there is the need for your suggestion.

The only issue I see here is how to deal with the import and export of symbols. I can imagine that on export, the absolute URL is exported (although specified as relative to a base URL) and on import, it is checked if there exists a URL in the project that is a prefix of the URL in the action and select this one. What do you think about this?

**Comment by Benuhx** [comment]
Would be great if you would implement it that way. Sounds really good :-)

**Comment by MazeChaZer** [comment]
Having multiple base URLs would be great :+1: 
I'm not sure if the automatic conversion to absolute URLs is a good idea. It might be surprising for the user that, if he forgets to configure the base URLs, some URLs are suddenly absolute. Another problem that I see is that the export results will be different depending on the configuration/environment. If I'm testing production and do an export, the export file will contain the URLs of the production environment. If I test locally, the URLs will be that of the local environment. That's why I would prefer that for each symbol the label of the base URL + the relative URL would be exported. If the base URL doesn't exist during import, an error would be thrown, saying which base URLs are missing. One requirement for this to work would be that the label of the base URL is a mandatory input. I would even go so far as to say that absolute URLs might not be needed at all. In most (if not all) cases it's better to use a base URL + relative path.

**Comment by MazeChaZer** [comment]
One small additional point: Automatic conversion to absolute URLs would not allow for base URLs like `http://localhost:3000/api/v1`, after one export/import the base URL would become `http://localhost:3000`.

**Comment by abainczyk** [comment]
This is implemented with 1b6ea8d3c5d1caec8c92799b8fee4e9e96860879
