### ISSUE TITLE
Bug: A user with the email already exists

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#50]
I've updated my local Alex Enviroment to the latest Docker-Version from learnlib/alex:unstable avaibale at 26.11.2019 23:00 Uhr.

After the update Alex fails to start with an exception:
"javax.validation.ValidationException: A user with the email already exists"

After i deleted the alex docker-volume the error was "fixed". However this is a bug in the current Alesx-Version. I've never created an User manually.

Full Exception and Stack Trace:
[logs.txt](https://github.com/LearnLib/alex/files/3894275/logs.txt)

**Comment by abainczyk** [comment]
Sorry this happend, user roles where not migrated correctly in one of the last commits which resulted in all admins to be normal users, thus your error. It was fixed in 6eb973c336577198e47f4ac177494378dea22381. You can also fix this manually in your database by setting the value for `role` to *2* for all admin users and to *1* for all non admin users in the table `users`.
